---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: animles
  labels:
    app: animles
spec:
  replicas: 3
  selector:
    matchLabels:
      app: animles
  template:
    metadata:
      labels:
        app: animles
    spec:
      containers:
      - name: animles
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
      - name: yanivomc
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: animles-service1
spec:
  ports:
  - name: svc-80
    protocol: TCP
    port: 80
    targetPort: 80
    type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: animles-service2
spec:
  ports:
  - name: svc-8080
    protocol: TCP
    port: 8080
    targetPort: 8080
    type: LoadBalancer
...
